name: northside_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # I moved http here. This is the correct place for packages your app uses.
  http: ^1.2.1 # Added a version number, which is good practice

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# This is the section you need to modify.
flutter:
  uses-material-design: true

  # This section tells Flutter to include your images in the app.
  # The indentation (two spaces) is VERY important.
  assets:
    - assets/images/
