name: stampede
description: "Stampede - Unofficial mobile app for Northside High School - Stay connected with announcements, athletics, events, and school news."

publish_to: 'none' 

version: 1.0.0+2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  sizer: ^2.0.15
  table_calendar: ^3.1.2
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.0.2+1
  flutter_dotenv: ^5.1.0
  
  webview_flutter: ^4.7.0
  webview_flutter_web: ^0.2.2
  
  # FIX: Replaced the non-working packages with the correct one.
  sticky_headers: ^0.3.0+2
  sliver_tools:
  figma_squircle: ^0.6.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.PNG"
  min_sdk_android: 21
  remove_alpha_ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/images/


# Keep the frontend package as is
frontend_package:
  git:
    url: https://github.com/NCP-Stampede/frontend_package.git
    ref: main

# UPDATE THE OVERRIDES SECTION AS WELL
dependency_overrides:
  frontend_package:
    path: ../frontend_package
