name: northside_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  sizer: ^2.0.15
  table_calendar: ^3.1.2

  # The main webview package and its web implementation
  webview_flutter: ^4.7.0
  webview_flutter_web: ^0.2.2

  # FIX: Add the Google Fonts package
  google_fonts: ^6.2.1

  flutter_lints:
  scrollable_positioned_list: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  http: ^1.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
