name: northside_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  sizer: ^2.0.15
  table_calendar: ^3.1.2
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  
  webview_flutter: ^4.7.0
  webview_flutter_web: ^0.2.2
  
  # FIX: Replaced the non-working packages with the correct one.
  sticky_headers: ^0.3.0+2
  sliver_tools:
  flutter_lints:

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
